package com.alien;
// Generated Feb 22, 2020 12:30:57 PM by Hibernate Tools 4.3.1



/**
 * Alien generated by hbm2java
 */
public class Alien  implements java.io.Serializable {


     private Integer alienId;
     private String alienName;
     private String alienLastName;
     private String alienColor;

    public Alien() {
    }

    public Alien(String alienName, String alienLastName, String alienColor) {
       this.alienName = alienName;
       this.alienLastName = alienLastName;
       this.alienColor = alienColor;
    }
   
    public Integer getAlienId() {
        return this.alienId;
    }
    
    public void setAlienId(Integer alienId) {
        this.alienId = alienId;
    }
    public String getAlienName() {
        return this.alienName;
    }
    
    public void setAlienName(String alienName) {
        this.alienName = alienName;
    }
    public String getAlienLastName() {
        return this.alienLastName;
    }
    
    public void setAlienLastName(String alienLastName) {
        this.alienLastName = alienLastName;
    }
    public String getAlienColor() {
        return this.alienColor;
    }
    
    public void setAlienColor(String alienColor) {
        this.alienColor = alienColor;
    }




}


